redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"

tests:
  image: python:2.7
  links:
    - redis:redis
  volumes:
    - .:/app
  working_dir: /app
  command: bash -c "pip install tox && tox"