# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import ella.core.cache.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20160203_1221'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('target_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Target id')),
                ('text', models.TextField(blank=True, verbose_name='Definition')),
                ('box_type', models.CharField(blank=True, max_length=200, verbose_name='Box type')),
                ('active_from', models.DateTimeField(blank=True, null=True, verbose_name='Position active from')),
                ('active_till', models.DateTimeField(blank=True, null=True, verbose_name='Position active till')),
                ('disabled', models.BooleanField(default=False, verbose_name='Disabled')),
                ('category', ella.core.cache.fields.CategoryForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Category')),
                ('target_ct', ella.core.cache.fields.ContentTypeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Target content type')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
            },
        ),
    ]
