# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_auto_20160203_1221'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('publishable_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.Publishable')),
                ('content', models.TextField(default=b'', verbose_name='Content')),
            ],
            options={
                'verbose_name': 'Article',
                'verbose_name_plural': 'Articles',
            },
            bases=('core.publishable',),
        ),
    ]
