# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:21
from __future__ import unicode_literals

import app_data.fields
import datetime
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc
import ella.core.cache.fields
import re


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('slug', models.SlugField(max_length=255, unique=True, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('text', models.TextField(blank=True, verbose_name='Text')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
            ],
            options={
                'verbose_name': 'Author',
                'verbose_name_plural': 'Authors',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, help_text='Description which can be used in link titles, syndication etc.', verbose_name='Description')),
                ('content', models.TextField(blank=True, default=b'', help_text='Optional content to use when rendering this category.', verbose_name='Content')),
                ('template', models.CharField(choices=[(b'category.html', 'default (category.html)')], default=b'category.html', help_text='Template to use to render detail page of this category.', max_length=100, verbose_name='Template')),
                ('slug', models.SlugField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile(b'^(?:[0-9]+[^0-9-]|[a-z])[a-z0-9-]*$'), 'Please enter a valid slug composed of lowecase letter, numbers and hyphens. First character must be a letter.', b'invalid')], verbose_name='Slug')),
                ('tree_path', models.CharField(editable=False, max_length=255, verbose_name='Path from root category')),
                ('app_data', app_data.fields.AppDataField(default=b'{}', editable=False, help_text='If you need to define custom data for category objects, you can use this field to do so.', verbose_name='Custom meta data')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_id', models.IntegerField()),
                ('dependent_id', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Dependency',
                'verbose_name_plural': 'Dependencies',
            },
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish_from', models.DateTimeField(db_index=True, verbose_name='Start of listing')),
                ('publish_to', models.DateTimeField(blank=True, null=True, verbose_name='End of listing')),
                ('commercial', models.BooleanField(default=False, help_text='Check this if the listing is of a commercial content.', verbose_name='Commercial')),
            ],
            options={
                'verbose_name': 'Listing',
                'verbose_name_plural': 'Listings',
            },
        ),
        migrations.CreateModel(
            name='Publishable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('slug', models.SlugField(max_length=255, validators=[django.core.validators.RegexValidator(re.compile('^[-a-zA-Z0-9_]+\\Z'), "Enter a valid 'slug' consisting of letters, numbers, underscores or hyphens.", 'invalid')], verbose_name='Slug')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('published', models.BooleanField(verbose_name='Published')),
                ('publish_from', models.DateTimeField(db_index=True, default=datetime.datetime(3000, 1, 1, 0, 0, tzinfo=utc), verbose_name='Publish from')),
                ('publish_to', models.DateTimeField(blank=True, null=True, verbose_name='End of visibility')),
                ('static', models.BooleanField(default=False, verbose_name='static')),
                ('last_updated', models.DateTimeField(blank=True, verbose_name='Last updated')),
                ('app_data', app_data.fields.AppDataField(default=b'{}', editable=False)),
                ('announced', models.BooleanField(default=False, editable=False, help_text=b'Publish signal sent')),
                ('authors', models.ManyToManyField(to='core.Author', verbose_name='Authors')),
                ('category', ella.core.cache.fields.CategoryForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Category')),
                ('content_type', ella.core.cache.fields.ContentTypeForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'verbose_name': 'Publishable object',
                'verbose_name_plural': 'Publishable objects',
            },
        ),
        migrations.CreateModel(
            name='Related',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('related_id', models.IntegerField(verbose_name='Object ID')),
                ('publishable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publishable', verbose_name='Publishable')),
                ('related_ct', ella.core.cache.fields.ContentTypeForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType', verbose_name='Content type')),
            ],
            options={
                'verbose_name': 'Related',
                'verbose_name_plural': 'Related',
            },
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Source',
                'verbose_name_plural': 'Sources',
            },
        ),
    ]
