# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import ella.core.cache.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
        ('sites', '0002_alter_domain_unique'),
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='publishable',
            name='photo',
            field=ella.core.cache.fields.CachedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Photo', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='publishable',
            name='source',
            field=ella.core.cache.fields.CachedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Source', verbose_name='Source'),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=ella.core.cache.fields.CategoryForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='listing',
            name='publishable',
            field=ella.core.cache.fields.CachedForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Publishable', verbose_name='Publishable'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='dependent_ct',
            field=ella.core.cache.fields.ContentTypeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depends_on_set', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='dependency',
            name='target_ct',
            field=ella.core.cache.fields.ContentTypeForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependency_for_set', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='category',
            name='site',
            field=ella.core.cache.fields.SiteForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='category',
            name='tree_parent',
            field=ella.core.cache.fields.CategoryForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Category', verbose_name='Parent category'),
        ),
        migrations.AddField(
            model_name='author',
            name='photo',
            field=ella.core.cache.fields.CachedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='photos.Photo', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='author',
            name='user',
            field=ella.core.cache.fields.CachedForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=set([('site', 'tree_path')]),
        ),
    ]
