# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-03 20:21
from __future__ import unicode_literals

import app_data.fields
from django.db import migrations, models
import django.db.models.deletion
import ella.photos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Format',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, verbose_name='Name')),
                ('max_width', models.PositiveIntegerField(verbose_name='Max width')),
                ('max_height', models.PositiveIntegerField(verbose_name='Max height')),
                ('flexible_height', models.BooleanField(help_text='Determines whether max_height is an absolute maximum, or the formattedphoto can vary from max_height to flexible_max_height.', verbose_name='Flexible height')),
                ('flexible_max_height', models.PositiveIntegerField(blank=True, null=True, verbose_name='Flexible max height')),
                ('stretch', models.BooleanField(verbose_name='Stretch')),
                ('nocrop', models.BooleanField(verbose_name='Do not crop')),
                ('resample_quality', models.IntegerField(choices=[(45, 'Low'), (65, 'Medium'), (75, 'Good'), (85, 'Better'), (95, 'High')], default=85, verbose_name='Resample quality')),
                ('master', models.ForeignKey(blank=True, help_text='When generating formatted image, use the image formatted to master format instead of the original.Useful when editors crop certain formats by hand and you wish to re-use those coordinates automatically.', null=True, on_delete=django.db.models.deletion.CASCADE, to='photos.Format', verbose_name='Master')),
                ('sites', models.ManyToManyField(to='sites.Site', verbose_name='Sites')),
            ],
            options={
                'verbose_name': 'Format',
                'verbose_name_plural': 'Formats',
            },
        ),
        migrations.CreateModel(
            name='FormatedPhoto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(height_field=b'height', max_length=300, upload_to=b'photos/%Y/%m/%d', width_field=b'width')),
                ('crop_left', models.IntegerField()),
                ('crop_top', models.IntegerField()),
                ('crop_width', models.IntegerField()),
                ('crop_height', models.IntegerField()),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('format', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Format')),
            ],
            options={
                'verbose_name': 'Formated photo',
                'verbose_name_plural': 'Formated photos',
            },
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('slug', models.SlugField(max_length=255, verbose_name='Slug')),
                ('image', models.ImageField(height_field=b'height', max_length=255, upload_to=ella.photos.models.upload_to, verbose_name='Image', width_field=b'width')),
                ('width', models.PositiveIntegerField(editable=False)),
                ('height', models.PositiveIntegerField(editable=False)),
                ('important_top', models.PositiveIntegerField(blank=True, null=True)),
                ('important_left', models.PositiveIntegerField(blank=True, null=True)),
                ('important_bottom', models.PositiveIntegerField(blank=True, null=True)),
                ('important_right', models.PositiveIntegerField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('app_data', app_data.fields.AppDataField(default=b'{}', editable=False)),
                ('authors', models.ManyToManyField(related_name='photo_set', to='core.Author', verbose_name='Authors')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.Source', verbose_name='Source')),
            ],
            options={
                'verbose_name': 'Photo',
                'verbose_name_plural': 'Photos',
            },
        ),
        migrations.AddField(
            model_name='formatedphoto',
            name='photo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='photos.Photo'),
        ),
        migrations.AlterUniqueTogether(
            name='formatedphoto',
            unique_together=set([('photo', 'format')]),
        ),
    ]
